
def node_require(script)  
   # Resolve script with node to allow for hoisting
   require Pod::Executable.execute_command('node', ['-p',
     "require.resolve(
       '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
 end

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

  
platform :ios, min_ios_version_supported
# use_modular_headers!
prepare_react_native_project!

rn_maps_path = '../node_modules/react-native-maps'
pod 'react-native-maps/Google', :path => rn_maps_path

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')
pod 'GoogleUtilities', :modular_headers => true 
pod 'FirebaseCore', :modular_headers => true    
pod 'FirebaseInstallations', :modular_headers => true    
pod 'GoogleDataTransport', :modular_headers => true    
pod 'nanopb', :modular_headers => true    
pod 'FirebaseCoreExtension', :modular_headers => true    




setup_permissions([
  'LocationWhenInUse',
])

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  $RNFirebaseAsStaticFramework = true
  use_frameworks! :linkage => :static
end


target 'rovin' do
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end



